<?php

namespace App\Http\Controllers;

use App\Models\Categoria;
use Illuminate\Http\Request;

class CategoriaProdutoController extends ModelController
{
    public function __construct() {
        $this->object = new Categoria();
        $this->objectName = 'categoria';
        $this->objectNames = 'categorias';
        $this->relactionships = ['produtos'];
    }

    /**
     * @ApiDescription (section = Categorias de Produtos, description="Retorna todos Categorias de Produtos")
     * @ApiMethod(type="get")
     * @ApiRoute(name="/api/categorias")
     * @ApiHeaders(name="Content-Type", type="application/json", descriptoin="Tipo de conteudo")
     */
    public function getAll(Request $request)
    {
        return parent::getAll($request); // TODO: Change the autogenerated stub
    }

    /**
     * @ApiDescription (section = Categorias de Produtos, description="Busca Um Determinado Categoria existente")
     * @ApiMethod(type="GET")
     * @ApiParams(name="id", type="integer", nullable=false, description="Categoria ID")
     * @ApiRoute(name="/api/categorias/{id}")
     * @ApiHeaders(name="Content-Type", type="application/json")
     */
    public function get($id)
    {
        return parent::get($id);
    }


    /** @ApiDescription (section = Categorias de Produtos, description="Actualiza um Categoria")
     * @ApiMethod(type="put")
     * @ApiRoute(name="/api/categorias/{id}")
     * @ApiHeaders(name="Content-Type", type="application/json")
     * @ApiParams(name="id", type="integer", nullable=false, description="Categoria ID")
     */
    public function update(Request $object, $id)
    {
        return parent::update($object, $id); // TODO: Change the autogenerated stub
    }


    /** @ApiDescription (section = Categorias de Produtos, description="Elimina um Categoria")
     * @ApiMethod(type="delete")
     * @ApiRoute(name="/api/categorias/{id}")
     * @ApiHeaders(name="Content-Type", type="application/json")
     * @ApiParams(name="id", type="integer", nullable=false, description="Categoria ID")
     */
    public function destroy(Request $objecto, $id)
    {
        return parent::destroy($objecto, $id); // TODO: Change the autogenerated stub
    }


}
