<?php

namespace App\Http\Controllers;

use App\Models\Produtore;
use Illuminate\Http\Request;


class ProdutorController extends ModelController
{
    public function __construct() {
        $this->object = new Produtore();
        $this->objectName = 'produtor';
        $this->objectNames = 'produtores';
        $this->relactionships = ['distrito', 'user', 'produtosProduzidos', 'ofertas'];
    }


    /**
     * @ApiDescription (section = Produtores, description="Retorna todos Produtores")
     * @ApiMethod(type="get")
     * @ApiRoute(name="/produtores")
     * @ApiHeaders(name="Content-Type", type="application/json", descriptoin="Tipo de conteudo")
     */
    public function getAll(Request $request)
    {
        return parent::getAll($request); // TODO: Change the autogenerated stub
    }

    /**
     * @ApiDescription (section = Produtores, description="Busca Uma Determinada Produtores existente")
     * @ApiMethod(type="GET")
     * @ApiParams(name="id", type="integer", nullable=false, description="Produtores ID")
     * @ApiRoute(name="/produtores/{id}")
     * @ApiHeaders(name="Content-Type", type="application/json", description="Tipo de Conteudo")
     */
    public function get($id)
    {
        return parent::get($id);
    }


    /**
     * @ApiDescription (section = Produtores, description="Cria uma nova Procura")
     * @ApiMethod(type="POST")
     * @ApiRoute(name="/produtores")
     * @ApiHeaders(name="Content-Type", type="application/json", description="Tipo de Conteudo")
     * @ApiParams(name="telefone", type="string", nullable=false, description="Numero de Telefone")
     * @ApiParams(name="users_id", type="integer", nullable=false, description="Id do Utilizador")
     * @ApiParams(name="distritos_id", type="integer", nullable=false, description="Id do Distrito do produtor")
     */
    public function store(Request $request)
    {
        return parent::store($request); // TODO: Change the autogenerated stub
    }

    /** @ApiDescription (section = Produtores, description="Actualiza uma Produtores")
     * @ApiMethod(type="put")
     * @ApiRoute(name="/produtores/{id}")
     * @ApiHeaders(name="Content-Type", type="application/json", description="Tipo de Conteudo")
     * @ApiParams(name="id", type="integer", nullable=false, description="Produtores ID")
     */
    public function update(Request $object, $id)
    {
        return parent::update($object, $id); // TODO: Change the autogenerated stub
    }


    /** @ApiDescription (section = Produtores, description="Elimina uma Produtores")
     * @ApiMethod(type="delete")
     * @ApiRoute(name="/produtores/{id}")
     * @ApiHeaders(name="Content-Type", type="application/json", description="Tipo de Conteudo")
     * @ApiParams(name="id", type="integer", nullable=false, description="Produtores ID")
     */
    public function destroy(Request $objecto, $id)
    {
        return parent::destroy($objecto, $id); // TODO: Change the autogenerated stub
    }






}
