<?php

namespace App\Http\Controllers;

use App\Models\Revendedore;
use Illuminate\Http\Request;

class RevendedorController extends ModelController
{
    public function __construct() {
        $this->object = new Revendedore();
        $this->objectName = 'revendedor';
        $this->objectNames = 'revendedores';
        $this->relactionships = ['user', 'mercado' => function($query){
            $query->with('distrito');
        }, 'interesses', 'procuras' => function($query){
            $query->with(['produto', 'unidades_medida']);
        }];
    }


    /**
     * @ApiDescription (section = Revendedores, description="Retorna todos Revendedores")
     * @ApiMethod(type="get")
     * @ApiRoute(name="/api/revendedores")
     * @ApiHeaders(name="Content-Type", type="application/json", descriptoin="Tipo de conteudo")
     */
    public function getAll(Request $request)
    {
        return parent::getAll($request); // TODO: Change the autogenerated stub
    }

    /**
     * @ApiDescription (section = Revendedores, description="Busca Uma Determinada Revendedores existente")
     * @ApiMethod(type="GET")
     * @ApiParams(name="id", type="integer", nullable=false, description="Revendedores ID")
     * @ApiRoute(name="/api/revendedores/{id}")
     * @ApiHeaders(name="Content-Type", type="application/json", description="Tipo de Conteudo")
     */
    public function get($id)
    {
        return parent::get($id);
    }


    /**
     * @ApiDescription (section = Revendedores, description="Cria uma nova Procura")
     * @ApiMethod(type="POST")
     * @ApiRoute(name="/api/revendedores")
     * @ApiHeaders(name="Content-Type", type="application/json", description="Tipo de Conteudo")
     * @ApiParams(name="telefone", type="string", nullable=false, description="Numero de Telefone")
     * @ApiParams(name="users_id", type="integer", nullable=false, description="Id do Utilizador")
     * @ApiParams(name="mercados_id", type="integer", nullable=false, description="Id do Mercado do revendedor")
     * @ApiParams(name="tipo_revendedor", type="ENUM - 'FABRICA','LOJA','INDIVIDUAL' ", nullable=false, description="Tipo de Revendedor")
     */
    public function store(Request $request)
    {
        return parent::store($request); // TODO: Change the autogenerated stub
    }

    /** @ApiDescription (section = Revendedores, description="Actualiza uma Revendedores")
     * @ApiMethod(type="put")
     * @ApiRoute(name="/api/revendedores/{id}")
     * @ApiHeaders(name="Content-Type", type="application/json", description="Tipo de Conteudo")
     * @ApiParams(name="id", type="integer", nullable=false, description="Revendedores ID")
     */
    public function update(Request $object, $id)
    {
        return parent::update($object, $id); // TODO: Change the autogenerated stub
    }


    /** @ApiDescription (section = Revendedores, description="Elimina uma Revendedores")
     * @ApiMethod(type="delete")
     * @ApiRoute(name="/api/revendedores/{id}")
     * @ApiHeaders(name="Content-Type", type="application/json", description="Tipo de Conteudo")
     * @ApiParams(name="id", type="integer", nullable=false, description="Revendedores ID")
     */
    public function destroy(Request $objecto, $id)
    {
        return parent::destroy($objecto, $id); // TODO: Change the autogenerated stub
    }




}
