<?php

namespace App\Http\Controllers;

use App\Models\UnidadesMedida;
use Illuminate\Http\Request;

class UnidadeMedidaController extends ModelController
{
    public function __construct() {
        $this->object = new UnidadesMedida();
        $this->objectName = 'unidade_medida';
        $this->objectNames = 'unidades_medidas';
        $this->relactionships = [];
    }


    /**
     * @ApiDescription (section = Unidades de Medida, description="Retorna todos Unidades de Medida")
     * @ApiMethod(type="get")
     * @ApiRoute(name="/api/unidades-medidas")
     * @ApiHeaders(name="Content-Type", type="application/json", descriptoin="Tipo de conteudo")
     */
    public function getAll(Request $request)
    {
        return parent::getAll($request); // TODO: Change the autogenerated stub
    }

    /**
     * @ApiDescription (section = Unidades de Medida, description="Busca Uma Determinada Unidades de Medida existente")
     * @ApiMethod(type="GET")
     * @ApiParams(name="id", type="integer", nullable=false, description="Unidades de Medida ID")
     * @ApiRoute(name="/api/unidades-medidas/{id}")
     * @ApiHeaders(name="Content-Type", type="application/json", description="Tipo de Conteudo")
     */
    public function get($id)
    {
        return parent::get($id);
    }


    /**
     * @ApiDescription (section = Unidades de Medida, description="Cria uma nova Procura")
     * @ApiMethod(type="POST")
     * @ApiRoute(name="/api/unidades-medidas")
     * @ApiHeaders(name="Content-Type", type="application/json", description="Tipo de Conteudo")
     * @ApiParams(name="username", type="string", nullable=false, description="Username / Numero de Telefone")
     * @ApiParams(name="password", type="string", nullable=false, description="Password")
     * @ApiParams(name="nome", type="string", nullable=false, description="Nome do Utilizador")
     * @ApiParams(name="foto", type="string ", nullable=false, description="Foto do Utilizador")
     */
    public function store(Request $request)
    {
        return parent::store($request); // TODO: Change the autogenerated stub
    }

    /** @ApiDescription (section = Unidades de Medida, description="Actualiza uma Unidades de Medida")
     * @ApiMethod(type="put")
     * @ApiRoute(name="/api/unidades-medidas/{id}")
     * @ApiHeaders(name="Content-Type", type="application/json", description="Tipo de Conteudo")
     * @ApiParams(name="id", type="integer", nullable=false, description="Unidades de Medida ID")
     */
    public function update(Request $object, $id)
    {
        return parent::update($object, $id); // TODO: Change the autogenerated stub
    }


    /** @ApiDescription (section = Unidades de Medida, description="Elimina uma Unidades de Medida")
     * @ApiMethod(type="delete")
     * @ApiRoute(name="/api/unidades-medidas/{id}")
     * @ApiHeaders(name="Content-Type", type="application/json", description="Tipo de Conteudo")
     * @ApiParams(name="id", type="integer", nullable=false, description="Unidades de Medida ID")
     */
    public function destroy(Request $objecto, $id)
    {
        return parent::destroy($objecto, $id); // TODO: Change the autogenerated stub
    }






}
